<a href="https://colab.research.google.com/github/riya461/Learn_ML/blob/main/Library/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [11]:
l1 = [1,2,3]
l2 = [4,5,6]


In [17]:
a1 = np.array(l1)
a2 = np.array(l2).reshape(3,1)

In [18]:
# dot product
dot = np.dot(a1,a2)
print(dot)


[32]


In [23]:
from timeit import default_timer as timer
a = np.random.rand(1000000)
b = np.random.rand(1000000)

A = list(a)
B = list(b)

T = 1000

def dot1():
  dot = 0
  for i in range(len(A)):
    dot += A[i]*B[i]
    return dot
def dot2():
  return np.dot(A,B)

start = timer()
for r in range(T):
  dot1()
end = timer()
t1 = end-start

start = timer()
for r in range(T):
  dot2()
end = timer()
t2 = end-start


print('list calc',t1)
print('np dot',t2)
print('ratio',t1/t2)

list calc 0.0007774819998758176
np dot 220.15002791999996
ratio 3.5316007325620046e-06


In [24]:
a = np.array([[1,2,3],[4,5,6]])
print(a[0][0])

1


In [27]:
a = np.array([[1,2],[3,4],[5,6]])
bool_idx = a > 2
print(bool_idx)
print(a[bool_idx])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]


In [30]:
even = np.argwhere(a%2==0).flatten()
print(even)

[0 1 1 1 2 1]


In [32]:
# reshape
a = np.arange(1,7)
print(a)
b = a.reshape(3,2)
print(b)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


In [33]:
b = a[np.newaxis,:]
print(b)

[[1 2 3 4 5 6]]


In [34]:
b = a[:,np.newaxis]
print(b)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [37]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])
c = np.concatenate((a,b),axis=0)
print(c)

[[1 2]
 [3 4]
 [5 6]]


In [39]:
c = np.concatenate((a,b.T),axis=1)
print(c)

[[1 2 5]
 [3 4 6]]


In [41]:
#  hstack
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.hstack((a,b))
print(c)

[1 2 3 4 5 6 7 8]


In [42]:
#   vstack
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.vstack((a,b))
print(c)

[[1 2 3 4]
 [5 6 7 8]]


In [45]:
x = np.array([[1,2,3],
             [4,5,6],
             [1,2,3],
             [4,5,6]])
a = np.array([1,0,1])
print(x+a)

[[2 2 4]
 [5 5 7]
 [2 2 4]
 [5 5 7]]


In [3]:
a = np.array([[7,8,9,10,11,12,13],[17,18,19,20,21,22,23]])
print(a.sum(axis=0))
print(a.sum(axis=1))

[24 26 28 30 32 34 36]
[ 70 140]


In [4]:
print(a.min())

7


In [5]:
print(np.max(a,axis=1))

[13 23]


In [6]:
a.dtype

dtype('int64')

In [7]:
b = a.copy()
b

array([[ 7,  8,  9, 10, 11, 12, 13],
       [17, 18, 19, 20, 21, 22, 23]])

In [9]:
b = a
b


array([[ 7,  8,  9, 10, 11, 12, 13],
       [17, 18, 19, 20, 21, 22, 23]])

Geerating arrays

In [10]:
a = np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [11]:
a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [12]:
a = np.full((2,3),5)
print(a)

[[5 5 5]
 [5 5 5]]


In [13]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
a = np.arange(1,7).reshape(2,3)
print(a)

[[1 2 3]
 [4 5 6]]


In [16]:
a = np.linspace(0,10,5)
print(a)

[ 0.   2.5  5.   7.5 10. ]


Random numbers

In [17]:
a = np.random.random((2,3))
print(a)

[[0.79552653 0.56875655 0.85165584]
 [0.46189065 0.66869901 0.65166518]]


In [18]:
a = np.random.randint(0,10,(2,3))
print(a)

[[0 8 0]
 [1 8 8]]


In [19]:
a = np.random.randn(2,3)
print(a)

[[ 0.5874441   0.03763478  0.76691389]
 [-0.85779157 -2.44765845 -1.56630127]]


Linear algebra

In [20]:
a = np.array([[1,2],[3,4]])
eigenvalues, eigenvectors = np.linalg.eig(a)
print(eigenvalues)
print(eigenvectors) # column vector

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [24]:
b = eigenvectors[:,0] * eigenvalues[0]
print(b)
c = a @ eigenvectors[:,0]
print(c)

[ 0.30697009 -0.21062466]
[ 0.30697009 -0.21062466]


In [26]:
print(np.allclose(b,c)) # b == c

True
